### ISSUE TITLE
Can't see icons - showing text instead (lazy loading)

### ISSUE THREAD

**Issue by pliablepixels** [zyra/ionic2-material-icons#5]
Hi, thanks for your work! I can't seem to see any icons (testing on a desktop). I am using lazy loading. Here is what I have so far:

package.json
```
 "config": {
              "ionic_copy": "./copy.config.js"
    },
```

cat copy.config.js 
```
module.exports = {
  copyMaterialIcons: {
    src: ['{{ROOT}}/node_modules/ionic2-material-icons/fonts/**/*'],
    dest: '{{WWW}}/assets/fonts'
  }
```

ls www/assets/fonts/

```
MaterialIcons-Regular.eot	ionicons.ttf			noto-sans.scss			roboto-medium.ttf
MaterialIcons-Regular.ttf	ionicons.woff			roboto-bold.ttf			roboto-medium.woff
MaterialIcons-Regular.woff	ionicons.woff2			roboto-bold.woff		roboto-medium.woff2
MaterialIcons-Regular.woff2	noto-sans-bold.ttf		roboto-bold.woff2		roboto-regular.ttf
ionicons.eot			noto-sans-bold.woff		roboto-light.ttf		roboto-regular.woff
ionicons.scss			noto-sans-regular.ttf		roboto-light.woff		roboto-regular.woff2
ionicons.svg			noto-sans-regular.woff		roboto-light.woff2		roboto.scss
```
So looks like the config is ok.

app.module.ts
```
import { MaterialIconsModule } from 'ionic2-material-icons';
```
also added `MaterialIconsModule` to `imports` of `app.module.ts`

Now in `foo.module.ts` (where I need to use the ion)
I added
```
import { MaterialIconsModule } from 'ionic2-material-icons';
```
also added `MaterialIconsModule` to `imports` of `foo.module.ts`

Finally, `foo.html`
```
<ion-icon md-name="settings"></ion-icon> Hello
```

Here is what I see (the name settings, not the icon:
<img width="136" alt="screen shot 2017-07-09 at 10 03 14 am" src="https://user-images.githubusercontent.com/4116654/27994528-e1622e30-648d-11e7-9e68-70c79b5d0b05.png">

ionic-info:
```
ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v8.1.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.2 
    npm        : 5.0.3 

```

Thanks

**Comment by ihadeed** [comment]
Thanks for reporting this. I'll take a look soon.

**Comment by pliablepixels** [comment]
Thanks! If it helps, my repo is open source and is [here](https://github.com/pliablepixels/medfolio). If you run it, go past the intro screen, tap on any category in the category screen, you will see a screen where I [try and display](https://github.com/pliablepixels/medfolio/blob/master/src/pages/medicalrecord/medicalrecord.html#L22-L24) both a font-awesome icon (which works) and a material icon using your lib, which currently does not.

**Comment by pliablepixels** [comment]
quick update - the icon does show up on the device (iOS), just not on the desktop browsers  (tried both Chrome and Safari)

![img_1248](https://user-images.githubusercontent.com/4116654/27997195-f7b8492a-64c0-11e7-8dd0-58400530ca08.PNG)

**Comment by bleuscyther** [comment]
it maybe due to the new `@ionic/app-scripts`  **2.0.0**

**Comment by ihadeed** [comment]
If this issue was introduced by `@ionic/app-scripts@2.0.0`, please update to `2.0.1` and let me know if you're still experiencing any issues.

**Comment by bleuscyther** [comment]
@ihadeed works now, thx

**Comment by razvantomegea** [comment]
I have `@ionic/app-scripts@2.1.3` and it doesn't work

**Comment by mukulpatlan** [comment]
not working with "@ionic/app-scripts": "3.1.9". Any support?
