### ISSUE TITLE
material icons are not appearing

### ISSUE THREAD

**Issue by dmoganty** [zyra/ionic2-material-icons#6]
I am not seeing material icons. The CSS properties of ion-icon were still showing from ionic. I inspect element and changed font-family to "material icons", it worked. 

ion-icon {
    display: inline-block;
    font-family: "Ionicons";
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-style: normal;
    font-variant: normal;
    font-weight: normal;
    line-height: 1;
    text-rendering: auto;
    text-transform: none;
    speak: none;
}

HTML code
<ion-icon md-name="{{p.icon}}"></ion-icon>

**Comment by ihadeed** [comment]
Did you import the `MaterialIconsModule` to your NgModule?
If you are using lazy loading, you need to have it imported in every module where you wish to use material icons.

**Comment by dmoganty** [comment]
Yes I did 

Directive was replacing the inner text.

Issue is with CSS

**Comment by dmoganty** [comment]
<img width="1432" alt="screen shot 2017-12-19 at 6 55 19 am" src="https://user-images.githubusercontent.com/31766021/34135995-c23bafaa-e489-11e7-8496-4d3a0a14e0f4.png">

**Comment by dmoganty** [comment]
it worked when I  added extra md-name

<ion-icon **md-name** [md-name]="p.icon" item-start></ion-icon>
